apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJZbVZzZVdGbGRpMWhMV2M2WjJod1gwOHhUMWwxVEVWRFZXTnBSRmx1T0haMFJqTnVVREpWTlZocFlYbHVXREV4U21wVGFRPT0iCiAgICB9CiAgfQp9Cg== 
type: kubernetes.io/dockerconfigjson
